<?php

return [
    'regions' => [
        [
            'slug' => 'east-africa',
            'name' => 'East Africa',
            'description' => 'World-class wildlife migrations, gorilla trekking, rift valley landscapes, and the easiest first step into an Africa safari journey.',
            'image' => 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1200&q=80',
            'countries' => ['Uganda', 'Kenya', 'Tanzania', 'Rwanda'],
        ],
        [
            'slug' => 'north-africa',
            'name' => 'North Africa',
            'description' => 'Golden dunes, imperial medinas, and ancient caravan routes from Morocco to Egypt.',
            'image' => 'https://images.unsplash.com/photo-1506929562872-bb421503ef21?auto=format&fit=crop&w=1200&q=80',
            'countries' => ['Morocco', 'Egypt', 'Tunisia', 'Algeria'],
        ],
        [
            'slug' => 'west-africa',
            'name' => 'West Africa',
            'description' => 'Atlantic coastlines, vibrant music, sacred forests, and warm community-led experiences.',
            'image' => 'https://images.unsplash.com/photo-1598875706250-21faaf804361?auto=format&fit=crop&w=1200&q=80',
            'countries' => ['Senegal', 'Ghana', 'Nigeria', 'Sierra Leone'],
        ],
        [
            'slug' => 'central-africa',
            'name' => 'Central Africa',
            'description' => 'Rainforest expeditions, gorilla tracking, and deeply rooted indigenous traditions.',
            'image' => 'https://images.unsplash.com/photo-1614463770168-e8eaef4fd0e8?auto=format&fit=crop&w=1200&q=80',
            'countries' => ['Rwanda', 'Cameroon', 'Gabon', 'DR Congo'],
        ],
        [
            'slug' => 'southern-africa',
            'name' => 'Southern Africa',
            'description' => 'Big-five safaris, dramatic waterfalls, wine valleys, and desert-meets-ocean road trips.',
            'image' => 'https://images.unsplash.com/photo-1472396961693-142e6e269027?auto=format&fit=crop&w=1200&q=80',
            'countries' => ['South Africa', 'Botswana', 'Namibia', 'Zimbabwe', 'Zambia'],
        ],
    ],

    'destinations' => [
        [
            'slug' => 'maasai-mara',
            'name' => 'Maasai Mara',
            'region' => 'east-africa',
            'country' => 'Kenya',
            'price' => 'midrange',
            'travel_style' => ['wildlife', 'photography', 'family'],
            'summary' => 'Endless grasslands, strong Big Five sightings, and front-row seats to the Great Migration in season.',
            'hero_image' => 'https://images.unsplash.com/photo-1547970810-dc1eac37d174?auto=format&fit=crop&w=1400&q=80',
            'map_embed_url' => 'https://www.openstreetmap.org/export/embed.html?bbox=34.6%2C-2.2%2C35.6%2C-0.8&layer=mapnik',
            'brief' => 'One of Kenya’s most iconic safari landscapes, the Maasai Mara is best known for sweeping savannah, excellent predator sightings, and seasonal migration drama.',
            'getting_there' => 'Reach the Mara by light aircraft from Nairobi for speed, or by road from Nairobi via Narok for a fuller overland safari journey.',
            'best_time' => 'July to October is most famous for migration viewing, while the shoulder seasons are often calmer and greener.',
        ],
        [
            'slug' => 'murchison-falls-national-park',
            'name' => 'Murchison Falls National Park',
            'region' => 'east-africa',
            'country' => 'Uganda',
            'price' => 'midrange',
            'travel_style' => ['wildlife', 'adventure', 'family'],
            'summary' => 'Uganda’s largest national park, anchored by the Nile exploding through a narrow gorge into one of the region’s most dramatic falls.',
            'hero_image' => 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&w=1400&q=80',
            'map_embed_url' => 'https://www.openstreetmap.org/export/embed.html?bbox=31.4%2C2.0%2C32.4%2C2.7&layer=mapnik',
            'brief' => 'Murchison is Uganda’s flagship savannah safari, mixing game drives, Nile boat cruises, birding, and waterfall drama in one easy circuit.',
            'getting_there' => 'Drive north from Kampala in about 4 to 5 hours to the southern gates, or fly from Entebbe or Kajjansi into Pakuba, Chobe, or Bugungu airstrips.',
            'best_time' => 'Wildlife viewing is especially easy in the drier months, though the park runs year-round and the river section remains a signature highlight.',
        ],
        [
            'slug' => 'bwindi-impenetrable-national-park',
            'name' => 'Bwindi Impenetrable National Park',
            'region' => 'east-africa',
            'country' => 'Uganda',
            'price' => 'luxury',
            'travel_style' => ['wildlife', 'conservation', 'adventure'],
            'summary' => 'A misty montane forest famous for mountain gorilla trekking, community encounters, and serious biodiversity.',
            'hero_image' => 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1400&q=80',
            'map_embed_url' => 'https://www.openstreetmap.org/export/embed.html?bbox=29.5%2C-1.2%2C29.9%2C-0.8&layer=mapnik',
            'brief' => 'Bwindi is one of Africa’s most powerful wildlife experiences, ideal for travelers prioritizing gorilla trekking and forest-based adventure.',
            'getting_there' => 'Travel by road from Entebbe or Kampala via southwestern Uganda, or use a scheduled domestic flight to nearby airstrips followed by a lodge transfer.',
            'best_time' => 'Tracking runs year-round, but dry conditions are generally easier underfoot than the wetter months.',
        ],
        [
            'slug' => 'amboseli-national-park',
            'name' => 'Amboseli National Park',
            'region' => 'east-africa',
            'country' => 'Kenya',
            'price' => 'midrange',
            'travel_style' => ['wildlife', 'photography', 'family'],
            'summary' => 'Big-elephant country with classic Kilimanjaro views, wetlands, and accessible safari circuits from Nairobi.',
            'hero_image' => 'https://images.unsplash.com/photo-1508672019048-805c876b67e2?auto=format&fit=crop&w=1400&q=80',
            'map_embed_url' => 'https://www.openstreetmap.org/export/embed.html?bbox=37.0%2C-2.9%2C37.7%2C-2.3&layer=mapnik',
            'brief' => 'Amboseli is especially rewarding for first-time safari travelers who want reliable elephant sightings and postcard mountain backdrops.',
            'getting_there' => 'Drive from Nairobi via Emali and the park gates, or fly into Kimana airstrip for a shorter transfer.',
            'best_time' => 'Dryer months are best for concentrated game viewing, while wet months can be greener and excellent for birdlife.',
        ],
        [
            'slug' => 'kruger-national-park',
            'name' => 'Kruger National Park',
            'region' => 'southern-africa',
            'country' => 'South Africa',
            'price' => 'luxury',
            'travel_style' => ['wildlife', 'romantic', 'family'],
            'summary' => 'Classic game drives with luxury lodges and strong conservation stories.',
            'hero_image' => 'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=1400&q=80',
            'map_embed_url' => 'https://www.openstreetmap.org/export/embed.html?bbox=31.0%2C-25.8%2C32.2%2C-23.8&layer=mapnik',
        ],
        [
            'slug' => 'okavango-delta',
            'name' => 'Okavango Delta',
            'region' => 'southern-africa',
            'country' => 'Botswana',
            'price' => 'luxury',
            'travel_style' => ['wildlife', 'slow-travel', 'photography'],
            'summary' => 'Water safaris through pristine channels with mokoro canoe adventures.',
            'hero_image' => 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&w=1400&q=80',
            'map_embed_url' => 'https://www.openstreetmap.org/export/embed.html?bbox=22.3%2C-20.6%2C24.7%2C-18.2&layer=mapnik',
        ],
        [
            'slug' => 'serengeti-national-park',
            'name' => 'Serengeti National Park',
            'region' => 'east-africa',
            'country' => 'Tanzania',
            'price' => 'midrange',
            'travel_style' => ['wildlife', 'adventure', 'photography'],
            'summary' => 'Legendary predator sightings and vast plains glowing at sunrise.',
            'hero_image' => 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&w=1400&q=80',
            'map_embed_url' => 'https://www.openstreetmap.org/export/embed.html?bbox=34.1%2C-3.2%2C35.5%2C-1.2&layer=mapnik',
        ],
        [
            'slug' => 'sahara-dunes',
            'name' => 'Sahara Dunes',
            'region' => 'north-africa',
            'country' => 'Morocco',
            'price' => 'budget',
            'travel_style' => ['desert', 'adventure', 'culture'],
            'summary' => 'Camel caravans, starlit camps, and cinematic desert landscapes.',
            'hero_image' => 'https://images.unsplash.com/photo-1454496522488-7a8e488e8606?auto=format&fit=crop&w=1400&q=80',
            'map_embed_url' => 'https://www.openstreetmap.org/export/embed.html?bbox=-5.9%2C30.7%2C-3.2%2C32.3&layer=mapnik',
        ],
        [
            'slug' => 'victoria-falls',
            'name' => 'Victoria Falls',
            'region' => 'southern-africa',
            'country' => 'Zimbabwe',
            'price' => 'midrange',
            'travel_style' => ['adventure', 'family', 'romantic'],
            'summary' => 'Thunderous cascades, rainforest trails, and river adventures.',
            'hero_image' => 'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=1400&q=80',
            'map_embed_url' => 'https://www.openstreetmap.org/export/embed.html?bbox=25.6%2C-18.1%2C26.0%2C-17.7&layer=mapnik',
        ],
        [
            'slug' => 'cape-town',
            'name' => 'Cape Town',
            'region' => 'southern-africa',
            'country' => 'South Africa',
            'price' => 'midrange',
            'travel_style' => ['culture', 'food', 'family'],
            'summary' => 'Ocean panoramas, mountain hikes, and world-class city energy.',
            'hero_image' => 'https://images.unsplash.com/photo-1576485290814-1c72aa4bbb8e?auto=format&fit=crop&w=1400&q=80',
            'map_embed_url' => 'https://www.openstreetmap.org/export/embed.html?bbox=18.2%2C-34.2%2C18.7%2C-33.7&layer=mapnik',
        ],
        [
            'slug' => 'volcanoes-national-park',
            'name' => 'Volcanoes National Park',
            'region' => 'central-africa',
            'country' => 'Rwanda',
            'price' => 'luxury',
            'travel_style' => ['wildlife', 'adventure', 'conservation'],
            'summary' => 'Gorilla trekking in misty forests with community-led conservation.',
            'hero_image' => 'https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?auto=format&fit=crop&w=1400&q=80',
            'map_embed_url' => 'https://www.openstreetmap.org/export/embed.html?bbox=29.4%2C-1.7%2C29.8%2C-1.2&layer=mapnik',
        ],
        [
            'slug' => 'sine-saloum',
            'name' => 'Sine-Saloum Delta',
            'region' => 'west-africa',
            'country' => 'Senegal',
            'price' => 'budget',
            'travel_style' => ['culture', 'slow-travel', 'community'],
            'summary' => 'Mangrove channels, birdlife, and immersive village hospitality.',
            'hero_image' => 'https://images.unsplash.com/photo-1521295121783-8a321d551ad2?auto=format&fit=crop&w=1400&q=80',
            'map_embed_url' => 'https://www.openstreetmap.org/export/embed.html?bbox=-16.9%2C13.6%2C-15.9%2C14.4&layer=mapnik',
        ],
    ],

    'tours' => [
        [
            'title' => 'Great Migration Game Drive',
            'destination_slug' => 'maasai-mara',
            'region' => 'east-africa',
            'country' => 'Kenya',
            'type' => 'game-drive',
            'budget' => 'midrange',
            'duration' => 5,
            'travel_style' => 'wildlife',
            'price_from' => '$1,150',
            'partner' => 'TravelPayouts',
            'image' => 'https://images.unsplash.com/photo-1576485290814-1c72aa4bbb8e?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'title' => 'Murchison Falls Nile & Game Drive Safari',
            'destination_slug' => 'murchison-falls-national-park',
            'region' => 'east-africa',
            'country' => 'Uganda',
            'type' => 'game-drive',
            'budget' => 'midrange',
            'duration' => 3,
            'travel_style' => 'wildlife',
            'price_from' => '$540',
            'partner' => 'TravelPayouts',
            'image' => 'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'title' => 'Bwindi Gorilla Trekking Escape',
            'destination_slug' => 'bwindi-impenetrable-national-park',
            'region' => 'east-africa',
            'country' => 'Uganda',
            'type' => 'trekking',
            'budget' => 'luxury',
            'duration' => 3,
            'travel_style' => 'conservation',
            'price_from' => '$1,680',
            'partner' => 'TravelPayouts',
            'image' => 'https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'title' => 'Amboseli Elephant Trails Safari',
            'destination_slug' => 'amboseli-national-park',
            'region' => 'east-africa',
            'country' => 'Kenya',
            'type' => 'game-drive',
            'budget' => 'midrange',
            'duration' => 2,
            'travel_style' => 'photography',
            'price_from' => '$420',
            'partner' => 'Viator',
            'image' => 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'title' => 'Serengeti Balloon & Bush Breakfast',
            'destination_slug' => 'serengeti-national-park',
            'region' => 'east-africa',
            'country' => 'Tanzania',
            'type' => 'adventure',
            'budget' => 'luxury',
            'duration' => 3,
            'travel_style' => 'photography',
            'price_from' => '$1,900',
            'partner' => 'GetYourGuide',
            'image' => 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'title' => 'Kruger Big Five Explorer',
            'destination_slug' => 'kruger-national-park',
            'region' => 'southern-africa',
            'country' => 'South Africa',
            'type' => 'game-drive',
            'budget' => 'luxury',
            'duration' => 4,
            'travel_style' => 'wildlife',
            'price_from' => '$2,250',
            'partner' => 'Viator',
            'image' => 'https://images.unsplash.com/photo-1549366021-9f761d450615?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'title' => 'Okavango Mokoro Safari',
            'destination_slug' => 'okavango-delta',
            'region' => 'southern-africa',
            'country' => 'Botswana',
            'type' => 'water-safari',
            'budget' => 'luxury',
            'duration' => 6,
            'travel_style' => 'slow-travel',
            'price_from' => '$3,100',
            'partner' => 'TravelPayouts',
            'image' => 'https://images.unsplash.com/photo-1489392191049-fc10c97e64b6?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'title' => 'Victoria Falls & Zambezi Adventure',
            'destination_slug' => 'victoria-falls',
            'region' => 'southern-africa',
            'country' => 'Zimbabwe',
            'type' => 'adventure',
            'budget' => 'midrange',
            'duration' => 3,
            'travel_style' => 'adventure',
            'price_from' => '$740',
            'partner' => 'GetYourGuide',
            'image' => 'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'title' => 'Sahara Nomad Desert Camp',
            'destination_slug' => 'sahara-dunes',
            'region' => 'north-africa',
            'country' => 'Morocco',
            'type' => 'desert',
            'budget' => 'budget',
            'duration' => 2,
            'travel_style' => 'culture',
            'price_from' => '$280',
            'partner' => 'Viator',
            'image' => 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'title' => 'Cape Peninsula Cultural Loop',
            'destination_slug' => 'cape-town',
            'region' => 'southern-africa',
            'country' => 'South Africa',
            'type' => 'cultural',
            'budget' => 'midrange',
            'duration' => 1,
            'travel_style' => 'culture',
            'price_from' => '$165',
            'partner' => 'TravelPayouts',
            'image' => 'https://images.unsplash.com/photo-1576485290814-1c72aa4bbb8e?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'title' => 'Volcanoes Gorilla Trekking Circuit',
            'destination_slug' => 'volcanoes-national-park',
            'region' => 'central-africa',
            'country' => 'Rwanda',
            'type' => 'trekking',
            'budget' => 'luxury',
            'duration' => 2,
            'travel_style' => 'conservation',
            'price_from' => '$1,450',
            'partner' => 'TravelPayouts',
            'image' => 'https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'title' => 'Sine-Saloum Mangrove Canoe Tour',
            'destination_slug' => 'sine-saloum',
            'region' => 'west-africa',
            'country' => 'Senegal',
            'type' => 'community',
            'budget' => 'budget',
            'duration' => 2,
            'travel_style' => 'community',
            'price_from' => '$190',
            'partner' => 'Viator',
            'image' => 'https://images.unsplash.com/photo-1493558103817-58b2924bce98?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
    ],

    'accommodations' => [
        [
            'name' => 'Savanna Sky Camp',
            'destination_slug' => 'maasai-mara',
            'region' => 'east-africa',
            'country' => 'Kenya',
            'price' => 'midrange',
            'travel_style' => 'wildlife',
            'type' => 'tented-camp',
            'nightly_from' => '$260',
            'image' => 'https://images.unsplash.com/photo-1519821172141-b5d8f3f0f5c8?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'name' => 'Paraa River Lodge',
            'destination_slug' => 'murchison-falls-national-park',
            'region' => 'east-africa',
            'country' => 'Uganda',
            'price' => 'midrange',
            'travel_style' => 'wildlife',
            'type' => 'safari-lodge',
            'nightly_from' => '$230',
            'image' => 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'name' => 'Bwindi Canopy Retreat',
            'destination_slug' => 'bwindi-impenetrable-national-park',
            'region' => 'east-africa',
            'country' => 'Uganda',
            'price' => 'luxury',
            'travel_style' => 'conservation',
            'type' => 'forest-lodge',
            'nightly_from' => '$540',
            'image' => 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'name' => 'Amboseli Plains Camp',
            'destination_slug' => 'amboseli-national-park',
            'region' => 'east-africa',
            'country' => 'Kenya',
            'price' => 'midrange',
            'travel_style' => 'photography',
            'type' => 'tented-camp',
            'nightly_from' => '$210',
            'image' => 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'name' => 'Serengeti Dawn Lodge',
            'destination_slug' => 'serengeti-national-park',
            'region' => 'east-africa',
            'country' => 'Tanzania',
            'price' => 'midrange',
            'travel_style' => 'family',
            'type' => 'lodge',
            'nightly_from' => '$220',
            'image' => 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'name' => 'Kruger Riverfront Suites',
            'destination_slug' => 'kruger-national-park',
            'region' => 'southern-africa',
            'country' => 'South Africa',
            'price' => 'luxury',
            'travel_style' => 'romantic',
            'type' => 'lodge',
            'nightly_from' => '$590',
            'image' => 'https://images.unsplash.com/photo-1501117716987-c8e1ecb2107f?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'name' => 'Okavango Drift Hideaway',
            'destination_slug' => 'okavango-delta',
            'region' => 'southern-africa',
            'country' => 'Botswana',
            'price' => 'luxury',
            'travel_style' => 'slow-travel',
            'type' => 'eco-camp',
            'nightly_from' => '$740',
            'image' => 'https://images.unsplash.com/photo-1470246973918-29a93221c455?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'name' => 'Victoria Falls View Inn',
            'destination_slug' => 'victoria-falls',
            'region' => 'southern-africa',
            'country' => 'Zimbabwe',
            'price' => 'midrange',
            'travel_style' => 'adventure',
            'type' => 'boutique-hotel',
            'nightly_from' => '$180',
            'image' => 'https://images.unsplash.com/photo-1439130490301-25e322d88054?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'name' => 'Erg Sunrise Desert Camp',
            'destination_slug' => 'sahara-dunes',
            'region' => 'north-africa',
            'country' => 'Morocco',
            'price' => 'budget',
            'travel_style' => 'adventure',
            'type' => 'desert-camp',
            'nightly_from' => '$95',
            'image' => 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'name' => 'Cape Coastline House',
            'destination_slug' => 'cape-town',
            'region' => 'southern-africa',
            'country' => 'South Africa',
            'price' => 'midrange',
            'travel_style' => 'culture',
            'type' => 'boutique-hotel',
            'nightly_from' => '$210',
            'image' => 'https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'name' => 'Volcanoes Forest Villas',
            'destination_slug' => 'volcanoes-national-park',
            'region' => 'central-africa',
            'country' => 'Rwanda',
            'price' => 'luxury',
            'travel_style' => 'conservation',
            'type' => 'eco-lodge',
            'nightly_from' => '$660',
            'image' => 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'name' => 'Sine-Saloum Mangrove Cabins',
            'destination_slug' => 'sine-saloum',
            'region' => 'west-africa',
            'country' => 'Senegal',
            'price' => 'budget',
            'travel_style' => 'community',
            'type' => 'guest-house',
            'nightly_from' => '$85',
            'image' => 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
    ],

    'restaurants' => [
        [
            'name' => 'Mara Fireside Table',
            'destination_slug' => 'maasai-mara',
            'region' => 'east-africa',
            'country' => 'Kenya',
            'price' => 'midrange',
            'travel_style' => 'food',
            'cuisine' => 'Kenyan grill and farm-to-table',
            'summary' => 'Bush-facing dining with nyama choma, seasonal greens, and sundowner service after game drives.',
            'signature' => 'Sunset tasting menu',
            'image' => 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'name' => 'Nile Deck Kitchen',
            'destination_slug' => 'murchison-falls-national-park',
            'region' => 'east-africa',
            'country' => 'Uganda',
            'price' => 'midrange',
            'travel_style' => 'food',
            'cuisine' => 'Ugandan regional and grill',
            'summary' => 'Relaxed lodge dining near the river with grilled tilapia, matoke, and sunset views after the falls cruise.',
            'signature' => 'Nile tilapia supper',
            'image' => 'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'name' => 'Bwindi Forest Table',
            'destination_slug' => 'bwindi-impenetrable-national-park',
            'region' => 'east-africa',
            'country' => 'Uganda',
            'price' => 'midrange',
            'travel_style' => 'food',
            'cuisine' => 'Farm-to-lodge cuisine',
            'summary' => 'A quiet forest-edge dining room serving produce-driven menus built for trekkers returning from the hills.',
            'signature' => 'Trek recovery lunch',
            'image' => 'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'name' => 'Kilimanjaro View Grill',
            'destination_slug' => 'amboseli-national-park',
            'region' => 'east-africa',
            'country' => 'Kenya',
            'price' => 'midrange',
            'travel_style' => 'food',
            'cuisine' => 'Kenyan lodge dining',
            'summary' => 'Open-air dinners with Kilimanjaro views, slow breakfasts, and a strong base for family safari evenings.',
            'signature' => 'Bush breakfast with mountain view',
            'image' => 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'name' => 'Serengeti Salt Kitchen',
            'destination_slug' => 'serengeti-national-park',
            'region' => 'east-africa',
            'country' => 'Tanzania',
            'price' => 'midrange',
            'travel_style' => 'food',
            'cuisine' => 'East African comfort food',
            'summary' => 'Relaxed lodge restaurant known for fresh tilapia, chapati breakfasts, and easy family dinners between drives.',
            'signature' => 'Swahili breakfast board',
            'image' => 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'name' => 'Cape Quarter Pantry',
            'destination_slug' => 'cape-town',
            'region' => 'southern-africa',
            'country' => 'South Africa',
            'price' => 'midrange',
            'travel_style' => 'food',
            'cuisine' => 'Cape Malay and modern South African',
            'summary' => 'A design-forward city stop for spice-rich plates, natural wine, and neighborhood storytelling.',
            'signature' => 'Cape Malay tasting supper',
            'image' => 'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'name' => 'Falls Market Kitchen',
            'destination_slug' => 'victoria-falls',
            'region' => 'southern-africa',
            'country' => 'Zimbabwe',
            'price' => 'midrange',
            'travel_style' => 'food',
            'cuisine' => 'Regional plates and riverside cocktails',
            'summary' => 'A lively pre- or post-activity stop for grilled fish, local produce, and Zambezi sundowners.',
            'signature' => 'Zambezi sunset dinner',
            'image' => 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'name' => 'Desert Lantern Supper Club',
            'destination_slug' => 'sahara-dunes',
            'region' => 'north-africa',
            'country' => 'Morocco',
            'price' => 'budget',
            'travel_style' => 'culture',
            'cuisine' => 'Berber home-style cooking',
            'summary' => 'Campfire dinners with tagines, mint tea, and live drumming under a clear desert sky.',
            'signature' => 'Tagine under the stars',
            'image' => 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'name' => 'Volcanoes Harvest Room',
            'destination_slug' => 'volcanoes-national-park',
            'region' => 'central-africa',
            'country' => 'Rwanda',
            'price' => 'luxury',
            'travel_style' => 'food',
            'cuisine' => 'Rwandan produce-led dining',
            'summary' => 'Elegant post-trek dinners focused on seasonal vegetables, coffee, and mountain views.',
            'signature' => 'Chef-led gorilla trek recovery menu',
            'image' => 'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
    ],

    'blog_categories' => [
        'Planning Tips',
        'Best Time to Visit',
        'Itineraries',
        'Safety',
        'Culture',
    ],

    'blog_posts' => [
        [
            'title' => 'How to Plan Your First East Africa Safari',
            'slug' => 'plan-first-east-africa-safari',
            'category' => 'Planning Tips',
            'region' => 'east-africa',
            'country' => 'Uganda',
            'excerpt' => 'How to choose between Uganda, Kenya, Tanzania, and Rwanda depending on wildlife goals, road time, and budget.',
            'read_time' => '8 min read',
            'image' => 'https://images.unsplash.com/photo-1549366021-9f761d450615?auto=format&fit=crop&w=900&q=80',
        ],
        [
            'title' => 'Uganda vs Kenya for a First-Time Safari',
            'slug' => 'uganda-vs-kenya-first-time-safari',
            'category' => 'Planning Tips',
            'region' => 'east-africa',
            'country' => 'Multi-country',
            'excerpt' => 'Choose Uganda for gorillas and Nile scenery, Kenya for migration drama and fast-access classic safaris.',
            'read_time' => '7 min read',
            'image' => 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80',
        ],
        [
            'title' => 'Best Time to Visit Southern Africa by Season',
            'slug' => 'best-time-southern-africa',
            'category' => 'Best Time to Visit',
            'region' => 'southern-africa',
            'country' => 'South Africa',
            'excerpt' => 'Dry-season wildlife vs green-season value: where each month shines.',
            'read_time' => '6 min read',
            'image' => 'https://images.unsplash.com/photo-1472396961693-142e6e269027?auto=format&fit=crop&w=900&q=80',
        ],
        [
            'title' => '10-Day Morocco to Sahara Itinerary',
            'slug' => 'morocco-sahara-itinerary',
            'category' => 'Itineraries',
            'region' => 'north-africa',
            'country' => 'Morocco',
            'excerpt' => 'From medinas to dunes with practical transport and camp planning.',
            'read_time' => '10 min read',
            'image' => 'https://images.unsplash.com/photo-1489493887464-892be6d1daae?auto=format&fit=crop&w=900&q=80',
        ],
        [
            'title' => 'Safety Basics for Multi-Country Africa Trips',
            'slug' => 'africa-trip-safety-basics',
            'category' => 'Safety',
            'region' => 'hybrid',
            'country' => 'Multi-country',
            'excerpt' => 'Smart transport choices, emergency planning, and document backups.',
            'read_time' => '7 min read',
            'image' => 'https://images.unsplash.com/photo-1527631746610-bca00a040d60?auto=format&fit=crop&w=900&q=80',
        ],
        [
            'title' => 'Cultural Etiquette with Local Communities',
            'slug' => 'cultural-etiquette-local-communities',
            'category' => 'Culture',
            'region' => 'west-africa',
            'country' => 'Senegal',
            'excerpt' => 'Respect-first travel tips for villages, guides, and homestay hosts.',
            'read_time' => '5 min read',
            'image' => 'https://images.unsplash.com/photo-1509099836639-18ba1795216d?auto=format&fit=crop&w=900&q=80',
        ],
    ],

    'local_experiences' => [
        [
            'name' => 'Maasai Storytelling Evening',
            'region' => 'east-africa',
            'country' => 'Kenya',
            'travel_style' => 'community',
            'type' => 'community-tour',
            'price' => 'midrange',
            'host' => 'Naserian Community Guides',
            'bio' => 'An elder-led evening around the fire sharing oral histories and music.',
            'image' => 'https://images.unsplash.com/photo-1509099836639-18ba1795216d?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'name' => 'Murchison Delta Boat Experience',
            'region' => 'east-africa',
            'country' => 'Uganda',
            'travel_style' => 'wildlife',
            'type' => 'boat-cruise',
            'price' => 'midrange',
            'host' => 'Nile Delta Ranger Guides',
            'bio' => 'Boat-based wildlife viewing focused on birdlife, hippos, crocodiles, and river-edge game.',
            'image' => 'https://images.unsplash.com/photo-1508672019048-805c876b67e2?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'name' => 'Bwindi Community Forest Walk',
            'region' => 'east-africa',
            'country' => 'Uganda',
            'travel_style' => 'community',
            'type' => 'guided-walk',
            'price' => 'midrange',
            'host' => 'Bwindi Community Hosts',
            'bio' => 'A slower-paced community walk pairing forest edge scenery with storytelling and local crafts.',
            'image' => 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'name' => 'Sahara Desert Family Camp',
            'region' => 'north-africa',
            'country' => 'Morocco',
            'travel_style' => 'adventure',
            'type' => 'homestay',
            'price' => 'budget',
            'host' => 'Ait Ouzina Desert Hosts',
            'bio' => 'Overnight camp hosted by a Berber family with local cuisine.',
            'image' => 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'name' => 'Cape Malay Culinary Walk',
            'region' => 'southern-africa',
            'country' => 'South Africa',
            'travel_style' => 'food',
            'type' => 'guided-walk',
            'price' => 'midrange',
            'host' => 'Bo-Kaap Local Collective',
            'bio' => 'Neighborhood food walk with heritage stories and local kitchens.',
            'image' => 'https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
        [
            'name' => 'Sine-Saloum Mangrove Homestay',
            'region' => 'west-africa',
            'country' => 'Senegal',
            'travel_style' => 'slow-travel',
            'type' => 'homestay',
            'price' => 'budget',
            'host' => 'Djiffer Women Cooperative',
            'bio' => 'Community homestay with canoeing, drumming, and mangrove restoration.',
            'image' => 'https://images.unsplash.com/photo-1493558103817-58b2924bce98?auto=format&fit=crop&w=900&q=80',
            'affiliate_link' => '{{travelpayouts-link}}',
        ],
    ],

    'activities' => [
        'maasai-mara' => [
            ['title' => 'Sunrise Balloon Flight', 'type' => 'Adventure', 'affiliate_link' => '{{travelpayouts-link}}'],
            ['title' => 'Conservation Learning Walk', 'type' => 'Education', 'affiliate_link' => '{{travelpayouts-link}}'],
            ['title' => 'Local Craft Market Visit', 'type' => 'Culture', 'affiliate_link' => '{{travelpayouts-link}}'],
        ],
        'murchison-falls-national-park' => [
            ['title' => 'Boat Cruise to the Base of the Falls', 'type' => 'Wildlife', 'affiliate_link' => '{{travelpayouts-link}}'],
            ['title' => 'Top of the Falls Hike', 'type' => 'Adventure', 'affiliate_link' => '{{travelpayouts-link}}'],
            ['title' => 'Delta Birding Excursion', 'type' => 'Birding', 'affiliate_link' => '{{travelpayouts-link}}'],
        ],
        'bwindi-impenetrable-national-park' => [
            ['title' => 'Mountain Gorilla Trekking', 'type' => 'Wildlife', 'affiliate_link' => '{{travelpayouts-link}}'],
            ['title' => 'Batwa Cultural Encounter', 'type' => 'Culture', 'affiliate_link' => '{{travelpayouts-link}}'],
            ['title' => 'Forest Waterfall Walk', 'type' => 'Adventure', 'affiliate_link' => '{{travelpayouts-link}}'],
        ],
        'amboseli-national-park' => [
            ['title' => 'Elephant-Focused Game Drive', 'type' => 'Wildlife', 'affiliate_link' => '{{travelpayouts-link}}'],
            ['title' => 'Observation Hill Sunset Stop', 'type' => 'Photography', 'affiliate_link' => '{{travelpayouts-link}}'],
            ['title' => 'Maasai Village Visit', 'type' => 'Culture', 'affiliate_link' => '{{travelpayouts-link}}'],
        ],
        'serengeti-national-park' => [
            ['title' => 'Predator Tracking Drive', 'type' => 'Wildlife', 'affiliate_link' => '{{travelpayouts-link}}'],
            ['title' => 'Bush Sundowner Picnic', 'type' => 'Leisure', 'affiliate_link' => '{{travelpayouts-link}}'],
            ['title' => 'Village Story Exchange', 'type' => 'Culture', 'affiliate_link' => '{{travelpayouts-link}}'],
        ],
    ],

    'destination_insights' => [
        'maasai-mara' => [
            ['label' => 'Best for', 'value' => 'Migration timing, first safaris, and classic wildlife photography'],
            ['label' => 'Trip rhythm', 'value' => '2 to 4 nights pairs well with Nairobi or a beach extension'],
            ['label' => 'Booking note', 'value' => 'Reserve peak migration lodges early and compare road versus fly-in logistics'],
        ],
        'murchison-falls-national-park' => [
            ['label' => 'Best for', 'value' => 'Travelers who want Nile scenery, wildlife, and good value in one Uganda circuit'],
            ['label' => 'Trip rhythm', 'value' => '2 to 3 nights fits neatly before or after Kibale or Ziwa Rhino Sanctuary'],
            ['label' => 'Booking note', 'value' => 'Boat cruise timing matters, so compare lodge location and game-drive sector before booking'],
        ],
        'bwindi-impenetrable-national-park' => [
            ['label' => 'Best for', 'value' => 'Gorilla trekking, conservation-focused travel, and intimate forest experiences'],
            ['label' => 'Trip rhythm', 'value' => '2 to 3 nights allows trekking plus recovery and community add-ons'],
            ['label' => 'Booking note', 'value' => 'Permit timing, sector choice, and lodge transfer times should be checked before you commit'],
        ],
        'amboseli-national-park' => [
            ['label' => 'Best for', 'value' => 'Short Kenya safaris with dramatic elephant photography and mountain backdrops'],
            ['label' => 'Trip rhythm', 'value' => '1 to 2 nights works well with Nairobi, Tsavo, or the Mara'],
            ['label' => 'Booking note', 'value' => 'Cloud cover affects Kilimanjaro views, so keep expectations flexible across seasons'],
        ],
        'serengeti-national-park' => [
            ['label' => 'Best for', 'value' => 'Predator sightings, wide-open plains, and multi-park circuit planning'],
            ['label' => 'Trip rhythm', 'value' => '3 to 5 nights works well with Ngorongoro or Tarangire'],
            ['label' => 'Booking note', 'value' => 'Choose camps based on migration movement, not just park name'],
        ],
        'cape-town' => [
            ['label' => 'Best for', 'value' => 'Urban travelers who want food, coast, wine, and day-trip variety'],
            ['label' => 'Trip rhythm', 'value' => '3 to 5 nights before or after safari is the sweet spot'],
            ['label' => 'Booking note', 'value' => 'Stay close to your preferred pace: city center, Atlantic Seaboard, or Winelands edge'],
        ],
        'victoria-falls' => [
            ['label' => 'Best for', 'value' => 'Adventure add-ons, short iconic stopovers, and couples trips'],
            ['label' => 'Trip rhythm', 'value' => '2 to 3 nights is usually enough unless you add Chobe or Hwange'],
            ['label' => 'Booking note', 'value' => 'Water levels change the experience dramatically, so plan activity mix by season'],
        ],
        'sahara-dunes' => [
            ['label' => 'Best for', 'value' => 'Desert landscapes, cultural immersion, and cinematic overland journeys'],
            ['label' => 'Trip rhythm', 'value' => '1 to 2 nights in camp works best inside a longer Morocco route'],
            ['label' => 'Booking note', 'value' => 'Compare standard camps versus premium camps carefully before clicking through'],
        ],
        'volcanoes-national-park' => [
            ['label' => 'Best for', 'value' => 'High-value gorilla trekking and conservation-focused travel'],
            ['label' => 'Trip rhythm', 'value' => '2 to 3 nights covers permits, recovery time, and community add-ons'],
            ['label' => 'Booking note', 'value' => 'Permit rules and lodge availability can change, so verify latest conditions before booking'],
        ],
    ],

    'local_voices' => [
        'maasai-mara' => [
            [
                'name' => 'Lemayian Ole Saitoti',
                'role' => 'Community Wildlife Guide',
                'bio' => 'Leads ethical wildlife experiences and supports youth ranger training.',
                'photo' => 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=300&q=80',
            ],
            [
                'name' => 'Naserian Group',
                'role' => 'Women-led Craft Cooperative',
                'bio' => 'Hosts cultural workshops and reinvests in local schools.',
                'photo' => 'https://images.unsplash.com/photo-1521119989659-a83eee488004?auto=format&fit=crop&w=300&q=80',
            ],
        ],
    ],

    'trust_signals' => [
        'Directory only - we redirect to trusted partners via TravelPayouts.',
        'Showcasing local guides, family hosts, and community-run experiences.',
        'Real traveler tips and transparent filters for smarter trip planning.',
    ],
];
