-- Additive parity migration for existing Trek Africa Guide projects.
create table if not exists public.districts (
  id bigint generated by default as identity primary key,
  country_id bigint not null references public.countries(id) on delete cascade,
  slug text not null, name text not null, overview text, aliases jsonb,
  sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique(country_id, slug)
);
alter table public.attractions add column if not exists district_id bigint references public.districts(id) on delete set null;
alter table public.accommodations add column if not exists district_id bigint references public.districts(id) on delete set null;
alter table public.restaurants add column if not exists district_id bigint references public.districts(id) on delete set null;
create table if not exists public.booking_offers (
  id bigint generated by default as identity primary key, offerable_type text not null, offerable_id bigint not null,
  provider text not null, label text not null, source_url text, stay22_provider text, affiliate_supported boolean not null default false,
  price_amount numeric(10,2), price_currency char(3), price_unit text, price_checked_at date, price_basis text,
  active boolean not null default true, sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists idx_booking_offers_offerable on public.booking_offers(offerable_type, offerable_id);
create index if not exists idx_booking_offers_provider_active on public.booking_offers(provider, active);
alter table public.districts enable row level security; alter table public.booking_offers enable row level security;
drop policy if exists "Public can read districts" on public.districts;
create policy "Public can read districts" on public.districts for select using (true);
drop policy if exists "Public can read booking offers" on public.booking_offers;
create policy "Public can read booking offers" on public.booking_offers for select using (true);
drop policy if exists "Authenticated users can manage booking offers" on public.booking_offers;
create policy "Authenticated users can manage booking offers" on public.booking_offers for all to authenticated using (true) with check (true);
