create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create table if not exists public.users (
    id bigint generated by default as identity primary key,
    name text not null,
    email text not null unique,
    email_verified_at timestamptz,
    password text not null,
    role text not null default 'viewer',
    remember_token text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.password_reset_tokens (
    email text primary key,
    token text not null,
    created_at timestamptz
);

create table if not exists public.sessions (
    id text primary key,
    user_id bigint references public.users(id) on delete set null,
    ip_address varchar(45),
    user_agent text,
    payload text not null,
    last_activity integer not null
);

create table if not exists public.site_settings (
    id bigint generated by default as identity primary key,
    group_name text not null default 'general',
    key text not null unique,
    value text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.page_sections (
    id bigint generated by default as identity primary key,
    page_key text not null,
    section_key text not null,
    eyebrow text,
    title text,
    body text,
    image_url text,
    meta jsonb,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.regions (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    name text not null,
    hero_title text not null,
    hero_text text not null,
    overview text not null,
    countries_intro text,
    hero_image_url text,
    hero_image_alt text,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.countries (
    id bigint generated by default as identity primary key,
    region_id bigint not null references public.regions(id) on delete cascade,
    slug text not null unique,
    name text not null,
    hero_title text not null,
    hero_text text not null,
    overview text not null,
    access_summary text,
    best_time text,
    planning_tips text,
    hero_image_url text,
    hero_image_alt text,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.attractions (
    id bigint generated by default as identity primary key,
    region_id bigint not null references public.regions(id) on delete cascade,
    country_id bigint not null references public.countries(id) on delete cascade,
    slug text not null unique,
    name text not null,
    location_name text,
    hero_image_url text,
    hero_image_alt text,
    listing_summary text not null,
    detail_intro text not null,
    full_description text,
    getting_there text,
    best_time text,
    practical_info text,
    gallery jsonb,
    highlights jsonb,
    rating numeric(3,1) not null default 4.6,
    review_count integer not null default 0,
    price_label text,
    booking_url text,
    featured boolean not null default false,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.accommodations (
    id bigint generated by default as identity primary key,
    region_id bigint not null references public.regions(id) on delete cascade,
    country_id bigint not null references public.countries(id) on delete cascade,
    attraction_id bigint references public.attractions(id) on delete set null,
    slug text not null unique,
    name text not null,
    property_type text,
    location_name text,
    hero_image_url text,
    hero_image_alt text,
    listing_summary text not null,
    detail_intro text not null,
    practical_info text,
    amenities jsonb,
    rating numeric(3,1) not null default 4.5,
    review_count integer not null default 0,
    price_label text,
    booking_url text,
    featured boolean not null default false,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.restaurants (
    id bigint generated by default as identity primary key,
    region_id bigint not null references public.regions(id) on delete cascade,
    country_id bigint not null references public.countries(id) on delete cascade,
    attraction_id bigint references public.attractions(id) on delete set null,
    slug text not null unique,
    name text not null,
    cuisine text,
    location_name text,
    signature_dish text,
    hero_image_url text,
    hero_image_alt text,
    listing_summary text not null,
    detail_intro text not null,
    practical_info text,
    rating numeric(3,1) not null default 4.4,
    review_count integer not null default 0,
    price_label text,
    booking_url text,
    featured boolean not null default false,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.tour_operators (
    id bigint generated by default as identity primary key,
    region_id bigint not null references public.regions(id) on delete cascade,
    country_id bigint not null references public.countries(id) on delete cascade,
    attraction_id bigint references public.attractions(id) on delete set null,
    slug text not null unique,
    name text not null,
    summary text not null,
    website_url text,
    booking_url text,
    hero_image_url text,
    hero_image_alt text,
    specialties jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_sessions_user_id on public.sessions(user_id);
create index if not exists idx_sessions_last_activity on public.sessions(last_activity);
create index if not exists idx_countries_region_id on public.countries(region_id);
create index if not exists idx_attractions_region_id on public.attractions(region_id);
create index if not exists idx_attractions_country_id on public.attractions(country_id);
create index if not exists idx_accommodations_country_id on public.accommodations(country_id);
create index if not exists idx_accommodations_attraction_id on public.accommodations(attraction_id);
create index if not exists idx_restaurants_country_id on public.restaurants(country_id);
create index if not exists idx_restaurants_attraction_id on public.restaurants(attraction_id);
create index if not exists idx_tour_operators_country_id on public.tour_operators(country_id);
create index if not exists idx_tour_operators_attraction_id on public.tour_operators(attraction_id);

drop trigger if exists set_updated_at_users on public.users;
create trigger set_updated_at_users before update on public.users for each row execute function public.set_updated_at();
drop trigger if exists set_updated_at_site_settings on public.site_settings;
create trigger set_updated_at_site_settings before update on public.site_settings for each row execute function public.set_updated_at();
drop trigger if exists set_updated_at_page_sections on public.page_sections;
create trigger set_updated_at_page_sections before update on public.page_sections for each row execute function public.set_updated_at();
drop trigger if exists set_updated_at_regions on public.regions;
create trigger set_updated_at_regions before update on public.regions for each row execute function public.set_updated_at();
drop trigger if exists set_updated_at_countries on public.countries;
create trigger set_updated_at_countries before update on public.countries for each row execute function public.set_updated_at();
drop trigger if exists set_updated_at_attractions on public.attractions;
create trigger set_updated_at_attractions before update on public.attractions for each row execute function public.set_updated_at();
drop trigger if exists set_updated_at_accommodations on public.accommodations;
create trigger set_updated_at_accommodations before update on public.accommodations for each row execute function public.set_updated_at();
drop trigger if exists set_updated_at_restaurants on public.restaurants;
create trigger set_updated_at_restaurants before update on public.restaurants for each row execute function public.set_updated_at();
drop trigger if exists set_updated_at_tour_operators on public.tour_operators;
create trigger set_updated_at_tour_operators before update on public.tour_operators for each row execute function public.set_updated_at();

alter table public.site_settings enable row level security;
alter table public.page_sections enable row level security;
alter table public.regions enable row level security;
alter table public.countries enable row level security;
alter table public.attractions enable row level security;
alter table public.accommodations enable row level security;
alter table public.restaurants enable row level security;
alter table public.tour_operators enable row level security;

drop policy if exists "Public can read site settings" on public.site_settings;
create policy "Public can read site settings"
on public.site_settings
for select
using (true);

drop policy if exists "Public can read page sections" on public.page_sections;
create policy "Public can read page sections"
on public.page_sections
for select
using (true);

drop policy if exists "Public can read regions" on public.regions;
create policy "Public can read regions"
on public.regions
for select
using (true);

drop policy if exists "Public can read countries" on public.countries;
create policy "Public can read countries"
on public.countries
for select
using (true);

drop policy if exists "Public can read attractions" on public.attractions;
create policy "Public can read attractions"
on public.attractions
for select
using (true);

drop policy if exists "Public can read accommodations" on public.accommodations;
create policy "Public can read accommodations"
on public.accommodations
for select
using (true);

drop policy if exists "Public can read restaurants" on public.restaurants;
create policy "Public can read restaurants"
on public.restaurants
for select
using (true);

drop policy if exists "Public can read tour operators" on public.tour_operators;
create policy "Public can read tour operators"
on public.tour_operators
for select
using (true);

insert into storage.buckets (id, name, public)
values
    ('media', 'media', true),
    ('branding', 'branding', true)
on conflict (id) do update
set public = excluded.public;

drop policy if exists "Public can view media assets" on storage.objects;
create policy "Public can view media assets"
on storage.objects
for select
using (bucket_id in ('media', 'branding'));

drop policy if exists "Authenticated users can upload media assets" on storage.objects;
create policy "Authenticated users can upload media assets"
on storage.objects
for insert
to authenticated
with check (bucket_id in ('media', 'branding'));

drop policy if exists "Authenticated users can update media assets" on storage.objects;
create policy "Authenticated users can update media assets"
on storage.objects
for update
to authenticated
using (bucket_id in ('media', 'branding'))
with check (bucket_id in ('media', 'branding'));

drop policy if exists "Authenticated users can delete media assets" on storage.objects;
create policy "Authenticated users can delete media assets"
on storage.objects
for delete
to authenticated
using (bucket_id in ('media', 'branding'));
