create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
    select coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') in ('admin', 'super_admin')
        or coalesce(auth.jwt() -> 'user_metadata' ->> 'role', '') in ('admin', 'super_admin');
$$;

create table if not exists public.supplier_commission_settings (
    id bigint generated by default as identity primary key,
    setting_key text not null unique,
    rate numeric(5,2) not null default 18.00 check (rate >= 0 and rate <= 50),
    description text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

insert into public.supplier_commission_settings (setting_key, rate, description)
values ('default', 18.00, 'Default Trek Africa Guide commission. Suppliers pay no listing or subscription fees; commission is charged only on fulfilled bookings.')
on conflict (setting_key) do update
set rate = excluded.rate,
    description = excluded.description,
    updated_at = now();

create table if not exists public.supplier_profiles (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null unique references auth.users(id) on delete cascade,
    business_name text not null,
    provider_kind text not null default 'company' check (provider_kind in ('company', 'individual')),
    provider_type text not null default 'tour_operator',
    contact_name text not null,
    contact_email text not null,
    phone text,
    website_url text,
    locations jsonb not null default '[]'::jsonb,
    registration_tax_number text,
    payout_method text not null default 'bank' check (payout_method in ('bank', 'mobile_money')),
    bank_details jsonb not null default '{}'::jsonb,
    mobile_money_details jsonb not null default '{}'::jsonb,
    liability_insurance_path text,
    logo_path text,
    profile_photo_path text,
    status text not null default 'pending_email_verification' check (status in ('pending_email_verification', 'pending_admin_review', 'approved', 'rejected', 'suspended')),
    commission_rate numeric(5,2) check (commission_rate >= 0 and commission_rate <= 50),
    approved_at timestamptz,
    rejected_at timestamptz,
    admin_notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.supplier_products (
    id uuid primary key default gen_random_uuid(),
    supplier_id uuid not null references public.supplier_profiles(id) on delete cascade,
    country_id bigint references public.countries(id) on delete set null,
    title text not null,
    slug text not null,
    service_type text not null default 'tour' check (service_type in ('tour', 'activity', 'accommodation', 'restaurant', 'experience', 'transfer', 'workshop')),
    category text not null default 'Safari',
    status text not null default 'draft' check (status in ('draft', 'pending_review', 'published', 'paused', 'rejected')),
    booking_mode text not null default 'direct' check (booking_mode in ('direct', 'affiliate')),
    affiliate_url text,
    description text not null,
    highlights jsonb not null default '[]'::jsonb,
    itinerary jsonb not null default '[]'::jsonb,
    included jsonb not null default '[]'::jsonb,
    excluded jsonb not null default '[]'::jsonb,
    duration text,
    min_group_size integer not null default 1 check (min_group_size > 0),
    max_group_size integer check (max_group_size is null or max_group_size >= min_group_size),
    languages jsonb not null default '["English"]'::jsonb,
    meeting_point text,
    base_price numeric(12,2) not null default 0 check (base_price >= 0),
    currency text not null default 'USD',
    pricing_tiers jsonb not null default '[]'::jsonb,
    availability jsonb not null default '{}'::jsonb,
    photos jsonb not null default '[]'::jsonb,
    videos jsonb not null default '[]'::jsonb,
    commission_rate numeric(5,2) check (commission_rate >= 0 and commission_rate <= 50),
    published_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (supplier_id, slug)
);

create table if not exists public.supplier_bookings (
    id uuid primary key default gen_random_uuid(),
    supplier_id uuid not null references public.supplier_profiles(id) on delete restrict,
    product_id uuid not null references public.supplier_products(id) on delete restrict,
    customer_name text not null,
    customer_email text not null,
    customer_phone text,
    booking_date date,
    guests integer not null default 1 check (guests > 0),
    status text not null default 'pending' check (status in ('pending', 'confirmed', 'completed', 'cancelled', 'refunded')),
    payment_status text not null default 'pending' check (payment_status in ('pending', 'authorized', 'paid', 'failed', 'refunded')),
    total_amount numeric(12,2) not null check (total_amount >= 0),
    currency text not null default 'USD',
    commission_rate numeric(5,2) not null default 18.00,
    commission_amount numeric(12,2) not null default 0,
    supplier_payout_amount numeric(12,2) not null default 0,
    payment_provider text,
    payment_reference text,
    completed_at timestamptz,
    payout_id uuid,
    audit jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.supplier_payouts (
    id uuid primary key default gen_random_uuid(),
    supplier_id uuid not null references public.supplier_profiles(id) on delete restrict,
    period_start date not null,
    period_end date not null,
    gross_amount numeric(12,2) not null default 0,
    commission_amount numeric(12,2) not null default 0,
    net_amount numeric(12,2) not null default 0,
    currency text not null default 'USD',
    status text not null default 'pending' check (status in ('pending', 'processing', 'paid', 'failed')),
    payout_method text not null default 'bank',
    reference text,
    receipt_url text,
    paid_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.supplier_bookings
    drop constraint if exists supplier_bookings_payout_id_fkey;

alter table public.supplier_bookings
    add constraint supplier_bookings_payout_id_fkey
    foreign key (payout_id) references public.supplier_payouts(id) on delete set null;

create table if not exists public.supplier_reviews (
    id uuid primary key default gen_random_uuid(),
    supplier_id uuid not null references public.supplier_profiles(id) on delete cascade,
    product_id uuid references public.supplier_products(id) on delete set null,
    booking_id uuid references public.supplier_bookings(id) on delete set null,
    customer_name text not null,
    rating integer not null check (rating between 1 and 5),
    comment text,
    status text not null default 'published' check (status in ('pending', 'published', 'hidden')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.supplier_notifications (
    id uuid primary key default gen_random_uuid(),
    supplier_id uuid not null references public.supplier_profiles(id) on delete cascade,
    type text not null default 'system',
    title text not null,
    body text,
    read_at timestamptz,
    created_at timestamptz not null default now()
);

create table if not exists public.supplier_notification_outbox (
    id uuid primary key default gen_random_uuid(),
    supplier_id uuid not null references public.supplier_profiles(id) on delete cascade,
    booking_id uuid references public.supplier_bookings(id) on delete cascade,
    channel text not null check (channel in ('email', 'sms')),
    recipient text not null,
    subject text,
    body text not null,
    status text not null default 'pending' check (status in ('pending', 'sent', 'failed')),
    provider_reference text,
    error_message text,
    sent_at timestamptz,
    created_at timestamptz not null default now()
);

create index if not exists idx_supplier_profiles_status on public.supplier_profiles(status);
create index if not exists idx_supplier_products_supplier_status on public.supplier_products(supplier_id, status);
create index if not exists idx_supplier_products_country on public.supplier_products(country_id);
create index if not exists idx_supplier_bookings_supplier_status on public.supplier_bookings(supplier_id, status);
create index if not exists idx_supplier_bookings_product on public.supplier_bookings(product_id);
create index if not exists idx_supplier_payouts_supplier_status on public.supplier_payouts(supplier_id, status);
create index if not exists idx_supplier_notification_outbox_status on public.supplier_notification_outbox(status, channel);

create or replace function public.effective_supplier_commission(p_supplier_id uuid, p_product_id uuid default null)
returns numeric
language sql
stable
as $$
    select coalesce(
        (select commission_rate from public.supplier_products where id = p_product_id),
        (select commission_rate from public.supplier_profiles where id = p_supplier_id),
        (select rate from public.supplier_commission_settings where setting_key = 'default'),
        18.00
    );
$$;

create or replace function public.calculate_supplier_booking_commission()
returns trigger
language plpgsql
as $$
declare
    rate numeric(5,2);
    commission numeric(12,2);
begin
    rate := public.effective_supplier_commission(new.supplier_id, new.product_id);
    commission := round(new.total_amount * (rate / 100), 2);

    new.commission_rate := rate;
    new.commission_amount := commission;
    new.supplier_payout_amount := round(new.total_amount - commission, 2);
    new.audit := coalesce(new.audit, '[]'::jsonb) || jsonb_build_object(
        'event', 'commission_calculated',
        'formula', 'supplier_payout_amount = total_amount - (total_amount * commission_rate / 100)',
        'total_amount', new.total_amount,
        'commission_rate', rate,
        'commission_amount', commission,
        'supplier_payout_amount', round(new.total_amount - commission, 2),
        'at', now()
    );

    return new;
end;
$$;

drop trigger if exists calculate_supplier_booking_commission_before_write on public.supplier_bookings;
create trigger calculate_supplier_booking_commission_before_write
before insert or update of total_amount, supplier_id, product_id
on public.supplier_bookings
for each row execute function public.calculate_supplier_booking_commission();

create or replace function public.queue_supplier_booking_notifications()
returns trigger
language plpgsql
as $$
declare
    supplier public.supplier_profiles;
    product public.supplier_products;
begin
    select * into supplier from public.supplier_profiles where id = new.supplier_id;
    select * into product from public.supplier_products where id = new.product_id;

    insert into public.supplier_notifications (supplier_id, type, title, body)
    values (
        new.supplier_id,
        'new_booking',
        'New booking received',
        concat('New ', product.title, ' booking for ', new.customer_name, '. Gross ', new.currency, ' ', new.total_amount, ', commission ', new.currency, ' ', new.commission_amount, ', net payout ', new.currency, ' ', new.supplier_payout_amount, '.')
    );

    insert into public.supplier_notification_outbox (supplier_id, booking_id, channel, recipient, subject, body)
    values (
        new.supplier_id,
        new.id,
        'email',
        supplier.contact_email,
        'New Trek Africa Guide booking',
        concat('You have a new booking for ', product.title, '. Net supplier payout after commission: ', new.currency, ' ', new.supplier_payout_amount, '.')
    );

    if supplier.phone is not null then
        insert into public.supplier_notification_outbox (supplier_id, booking_id, channel, recipient, body)
        values (
            new.supplier_id,
            new.id,
            'sms',
            supplier.phone,
            concat('Trek Africa Guide booking: ', product.title, '. Net payout ', new.currency, ' ', new.supplier_payout_amount, '.')
        );
    end if;

    return new;
end;
$$;

drop trigger if exists queue_supplier_booking_notifications_after_insert on public.supplier_bookings;
create trigger queue_supplier_booking_notifications_after_insert
after insert on public.supplier_bookings
for each row execute function public.queue_supplier_booking_notifications();

create or replace function public.complete_supplier_booking(p_booking_id uuid)
returns public.supplier_bookings
language plpgsql
security definer
set search_path = public
as $$
declare
    booking public.supplier_bookings;
begin
    update public.supplier_bookings
    set status = 'completed',
        payment_status = 'paid',
        completed_at = coalesce(completed_at, now()),
        audit = audit || jsonb_build_object('event', 'booking_completed', 'at', now(), 'actor', auth.uid())
    where id = p_booking_id
      and (public.is_admin() or supplier_id in (select id from public.supplier_profiles where user_id = auth.uid()))
    returning * into booking;

    if booking.id is null then
        raise exception 'Booking not found or not allowed';
    end if;

    return booking;
end;
$$;

create or replace function public.create_supplier_monthly_payout(
    p_supplier_id uuid,
    p_period_start date,
    p_period_end date
)
returns public.supplier_payouts
language plpgsql
security definer
set search_path = public
as $$
declare
    payout public.supplier_payouts;
begin
    if not public.is_admin() then
        raise exception 'Only admins can create payout batches';
    end if;

    insert into public.supplier_payouts (
        supplier_id,
        period_start,
        period_end,
        gross_amount,
        commission_amount,
        net_amount,
        currency,
        payout_method
    )
    select
        p_supplier_id,
        p_period_start,
        p_period_end,
        coalesce(sum(total_amount), 0),
        coalesce(sum(commission_amount), 0),
        coalesce(sum(supplier_payout_amount), 0),
        coalesce(max(currency), 'USD'),
        coalesce((select payout_method from public.supplier_profiles where id = p_supplier_id), 'bank')
    from public.supplier_bookings
    where supplier_id = p_supplier_id
      and status = 'completed'
      and payment_status = 'paid'
      and payout_id is null
      and completed_at::date between p_period_start and p_period_end
    returning * into payout;

    update public.supplier_bookings
    set payout_id = payout.id,
        audit = audit || jsonb_build_object('event', 'attached_to_payout', 'payout_id', payout.id, 'at', now())
    where supplier_id = p_supplier_id
      and status = 'completed'
      and payment_status = 'paid'
      and payout_id is null
      and completed_at::date between p_period_start and p_period_end;

    return payout;
end;
$$;

create or replace function public.mark_supplier_payout_paid(
    p_payout_id uuid,
    p_reference text,
    p_receipt_url text default null
)
returns public.supplier_payouts
language plpgsql
security definer
set search_path = public
as $$
declare
    payout public.supplier_payouts;
begin
    if not public.is_admin() then
        raise exception 'Only admins can mark payouts paid';
    end if;

    update public.supplier_payouts
    set status = 'paid',
        reference = p_reference,
        receipt_url = p_receipt_url,
        paid_at = now()
    where id = p_payout_id
    returning * into payout;

    return payout;
end;
$$;

do $$
declare
    table_name text;
begin
    foreach table_name in array array[
        'supplier_commission_settings',
        'supplier_profiles',
        'supplier_products',
        'supplier_bookings',
        'supplier_payouts',
        'supplier_reviews'
    ]
    loop
        execute format('drop trigger if exists set_updated_at_%I on public.%I', table_name, table_name);
        execute format('create trigger set_updated_at_%I before update on public.%I for each row execute function public.set_updated_at()', table_name, table_name);
    end loop;
end;
$$;

alter table public.supplier_commission_settings enable row level security;
alter table public.supplier_profiles enable row level security;
alter table public.supplier_products enable row level security;
alter table public.supplier_bookings enable row level security;
alter table public.supplier_payouts enable row level security;
alter table public.supplier_reviews enable row level security;
alter table public.supplier_notifications enable row level security;
alter table public.supplier_notification_outbox enable row level security;

drop policy if exists "Admins manage commission settings" on public.supplier_commission_settings;
create policy "Admins manage commission settings" on public.supplier_commission_settings
for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Suppliers read own profile" on public.supplier_profiles;
create policy "Suppliers read own profile" on public.supplier_profiles
for select to authenticated using (user_id = auth.uid() or public.is_admin());

drop policy if exists "Suppliers create own profile" on public.supplier_profiles;
create policy "Suppliers create own profile" on public.supplier_profiles
for insert to authenticated with check (user_id = auth.uid());

drop policy if exists "Suppliers update own unapproved profile" on public.supplier_profiles;
create policy "Suppliers update own unapproved profile" on public.supplier_profiles
for update to authenticated
using (user_id = auth.uid() or public.is_admin())
with check ((user_id = auth.uid() and status in ('pending_email_verification', 'pending_admin_review')) or public.is_admin());

drop policy if exists "Public can read published supplier products" on public.supplier_products;
create policy "Public can read published supplier products" on public.supplier_products
for select using (status = 'published' or public.is_admin() or supplier_id in (select id from public.supplier_profiles where user_id = auth.uid()));

drop policy if exists "Approved suppliers manage own products" on public.supplier_products;
create policy "Approved suppliers manage own products" on public.supplier_products
for all to authenticated
using (supplier_id in (select id from public.supplier_profiles where user_id = auth.uid() and status = 'approved') or public.is_admin())
with check (supplier_id in (select id from public.supplier_profiles where user_id = auth.uid() and status = 'approved') or public.is_admin());

drop policy if exists "Suppliers and admins read bookings" on public.supplier_bookings;
create policy "Suppliers and admins read bookings" on public.supplier_bookings
for select to authenticated
using (supplier_id in (select id from public.supplier_profiles where user_id = auth.uid()) or public.is_admin());

drop policy if exists "Admins and service role manage bookings" on public.supplier_bookings;
create policy "Admins and service role manage bookings" on public.supplier_bookings
for all to authenticated
using (public.is_admin() or supplier_id in (select id from public.supplier_profiles where user_id = auth.uid()))
with check (public.is_admin() or supplier_id in (select id from public.supplier_profiles where user_id = auth.uid()));

drop policy if exists "Suppliers and admins read payouts" on public.supplier_payouts;
create policy "Suppliers and admins read payouts" on public.supplier_payouts
for select to authenticated
using (supplier_id in (select id from public.supplier_profiles where user_id = auth.uid()) or public.is_admin());

drop policy if exists "Admins manage payouts" on public.supplier_payouts;
create policy "Admins manage payouts" on public.supplier_payouts
for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Public can read published reviews" on public.supplier_reviews;
create policy "Public can read published reviews" on public.supplier_reviews
for select using (status = 'published' or public.is_admin() or supplier_id in (select id from public.supplier_profiles where user_id = auth.uid()));

drop policy if exists "Admins manage reviews" on public.supplier_reviews;
create policy "Admins manage reviews" on public.supplier_reviews
for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Suppliers read own notifications" on public.supplier_notifications;
create policy "Suppliers read own notifications" on public.supplier_notifications
for select to authenticated
using (supplier_id in (select id from public.supplier_profiles where user_id = auth.uid()) or public.is_admin());

drop policy if exists "Suppliers update own notifications" on public.supplier_notifications;
create policy "Suppliers update own notifications" on public.supplier_notifications
for update to authenticated
using (supplier_id in (select id from public.supplier_profiles where user_id = auth.uid()) or public.is_admin())
with check (supplier_id in (select id from public.supplier_profiles where user_id = auth.uid()) or public.is_admin());

drop policy if exists "Admins manage notification outbox" on public.supplier_notification_outbox;
create policy "Admins manage notification outbox" on public.supplier_notification_outbox
for all to authenticated using (public.is_admin()) with check (public.is_admin());

insert into storage.buckets (id, name, public)
values
    ('supplier-media', 'supplier-media', true),
    ('supplier-documents', 'supplier-documents', false)
on conflict (id) do update
set public = excluded.public;

drop policy if exists "Public can view supplier media" on storage.objects;
create policy "Public can view supplier media" on storage.objects
for select using (bucket_id = 'supplier-media');

drop policy if exists "Suppliers can view own private supplier documents" on storage.objects;
create policy "Suppliers can view own private supplier documents" on storage.objects
for select to authenticated
using (
    bucket_id = 'supplier-documents'
    and ((storage.foldername(name))[1] = auth.uid()::text or public.is_admin())
);

drop policy if exists "Suppliers upload supplier media" on storage.objects;
create policy "Suppliers upload supplier media" on storage.objects
for insert to authenticated
with check (
    bucket_id = 'supplier-media'
    or (bucket_id = 'supplier-documents' and (storage.foldername(name))[1] = auth.uid()::text)
);

drop policy if exists "Suppliers update supplier storage" on storage.objects;
create policy "Suppliers update supplier storage" on storage.objects
for update to authenticated
using (
    bucket_id = 'supplier-media'
    or (bucket_id = 'supplier-documents' and ((storage.foldername(name))[1] = auth.uid()::text or public.is_admin()))
)
with check (
    bucket_id = 'supplier-media'
    or (bucket_id = 'supplier-documents' and ((storage.foldername(name))[1] = auth.uid()::text or public.is_admin()))
);
